# -*- coding: utf-8 -*-

ID = 'ID'
YEAR = 'Year'
ISIN = 'ISIN'
EBITDA = 'EBITDA'
EBIT = 'EBIT'
EBT = 'EBT'
NET_INCOME = 'Net Income'
TOT_REVENUE = 'Tot Revenue'
TOT_DEBT = 'Tot Debt'
ACC_RECEIVABLE = 'Acc Receivable'
ACC_PAYABLE = 'Acc Payable'
TOT_INVENTORY = 'Tot Inventory'
COGS = 'COGS'
ENTERPR_VALUE = 'Enterpr Value'
NET_DEBT = 'Net Debt'
TOT_CURR_ASSETS = 'Tot Curr Assets'
TOT_CURR_LIABILITIES = 'Tot Curr Liabilities'
TOT_LIABILITIES = 'Tot Liabilities'
TOT_EQUITY = 'Tot Equity'
TOT_COMMON_STOCK = 'Tot Common Stock'
SHARES_OUT = 'Shares Out'
CASH_N_EQUIVALENTS = 'Cash & Equivalents'
NUM_EMPLOYEES = 'Number of Employees'